version: "3.5"

services:
  db:
    container_name: db_async
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 1
    volumes:
    - pgdata_async:/var/lib/postgresql/data/

  pg4:
    container_name: pg4_async
    image: thajeztah/pgadmin4
    ports:
      - 5050:5050

volumes:
  pgdata_async:
